// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOTValue.proto

package com.haro.netty.iot.staticOfFinal.proto;

public final class IOTValueProto {
  private IOTValueProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IOTValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IOTValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes frame_head = 1;</code>
     */
    com.google.protobuf.ByteString getFrameHead();

    /**
     * <code>bytes dir = 2;</code>
     */
    com.google.protobuf.ByteString getDir();

    /**
     * <code>bytes CommunicationID = 3;</code>
     */
    com.google.protobuf.ByteString getCommunicationID();

    /**
     * <code>bytes SIMCCID = 4;</code>
     */
    com.google.protobuf.ByteString getSIMCCID();

    /**
     * <code>bytes Produc = 5;</code>
     */
    com.google.protobuf.ByteString getProduc();

    /**
     * <code>bytes comm = 6;</code>
     */
    com.google.protobuf.ByteString getComm();

    /**
     * <code>bytes data_length = 7;</code>
     */
    com.google.protobuf.ByteString getDataLength();

    /**
     * <code>bytes data = 8;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bytes frame_tail = 9;</code>
     */
    com.google.protobuf.ByteString getFrameTail();
  }
  /**
   * Protobuf type {@code IOTValue}
   */
  public  static final class IOTValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IOTValue)
      IOTValueOrBuilder {
    // Use IOTValue.newBuilder() to construct.
    private IOTValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IOTValue() {
      frameHead_ = com.google.protobuf.ByteString.EMPTY;
      dir_ = com.google.protobuf.ByteString.EMPTY;
      communicationID_ = com.google.protobuf.ByteString.EMPTY;
      sIMCCID_ = com.google.protobuf.ByteString.EMPTY;
      produc_ = com.google.protobuf.ByteString.EMPTY;
      comm_ = com.google.protobuf.ByteString.EMPTY;
      dataLength_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
      frameTail_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private IOTValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              frameHead_ = input.readBytes();
              break;
            }
            case 18: {

              dir_ = input.readBytes();
              break;
            }
            case 26: {

              communicationID_ = input.readBytes();
              break;
            }
            case 34: {

              sIMCCID_ = input.readBytes();
              break;
            }
            case 42: {

              produc_ = input.readBytes();
              break;
            }
            case 50: {

              comm_ = input.readBytes();
              break;
            }
            case 58: {

              dataLength_ = input.readBytes();
              break;
            }
            case 66: {

              data_ = input.readBytes();
              break;
            }
            case 74: {

              frameTail_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IOTValueProto.internal_static_IOTValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IOTValueProto.internal_static_IOTValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IOTValue.class, Builder.class);
    }

    public static final int FRAME_HEAD_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString frameHead_;
    /**
     * <code>bytes frame_head = 1;</code>
     */
    public com.google.protobuf.ByteString getFrameHead() {
      return frameHead_;
    }

    public static final int DIR_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString dir_;
    /**
     * <code>bytes dir = 2;</code>
     */
    public com.google.protobuf.ByteString getDir() {
      return dir_;
    }

    public static final int COMMUNICATIONID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString communicationID_;
    /**
     * <code>bytes CommunicationID = 3;</code>
     */
    public com.google.protobuf.ByteString getCommunicationID() {
      return communicationID_;
    }

    public static final int SIMCCID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString sIMCCID_;
    /**
     * <code>bytes SIMCCID = 4;</code>
     */
    public com.google.protobuf.ByteString getSIMCCID() {
      return sIMCCID_;
    }

    public static final int PRODUC_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString produc_;
    /**
     * <code>bytes Produc = 5;</code>
     */
    public com.google.protobuf.ByteString getProduc() {
      return produc_;
    }

    public static final int COMM_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString comm_;
    /**
     * <code>bytes comm = 6;</code>
     */
    public com.google.protobuf.ByteString getComm() {
      return comm_;
    }

    public static final int DATA_LENGTH_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString dataLength_;
    /**
     * <code>bytes data_length = 7;</code>
     */
    public com.google.protobuf.ByteString getDataLength() {
      return dataLength_;
    }

    public static final int DATA_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 8;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int FRAME_TAIL_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString frameTail_;
    /**
     * <code>bytes frame_tail = 9;</code>
     */
    public com.google.protobuf.ByteString getFrameTail() {
      return frameTail_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!frameHead_.isEmpty()) {
        output.writeBytes(1, frameHead_);
      }
      if (!dir_.isEmpty()) {
        output.writeBytes(2, dir_);
      }
      if (!communicationID_.isEmpty()) {
        output.writeBytes(3, communicationID_);
      }
      if (!sIMCCID_.isEmpty()) {
        output.writeBytes(4, sIMCCID_);
      }
      if (!produc_.isEmpty()) {
        output.writeBytes(5, produc_);
      }
      if (!comm_.isEmpty()) {
        output.writeBytes(6, comm_);
      }
      if (!dataLength_.isEmpty()) {
        output.writeBytes(7, dataLength_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(8, data_);
      }
      if (!frameTail_.isEmpty()) {
        output.writeBytes(9, frameTail_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!frameHead_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, frameHead_);
      }
      if (!dir_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, dir_);
      }
      if (!communicationID_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, communicationID_);
      }
      if (!sIMCCID_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, sIMCCID_);
      }
      if (!produc_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, produc_);
      }
      if (!comm_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, comm_);
      }
      if (!dataLength_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, dataLength_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, data_);
      }
      if (!frameTail_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, frameTail_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IOTValue)) {
        return super.equals(obj);
      }
      IOTValue other = (IOTValue) obj;

      boolean result = true;
      result = result && getFrameHead()
          .equals(other.getFrameHead());
      result = result && getDir()
          .equals(other.getDir());
      result = result && getCommunicationID()
          .equals(other.getCommunicationID());
      result = result && getSIMCCID()
          .equals(other.getSIMCCID());
      result = result && getProduc()
          .equals(other.getProduc());
      result = result && getComm()
          .equals(other.getComm());
      result = result && getDataLength()
          .equals(other.getDataLength());
      result = result && getData()
          .equals(other.getData());
      result = result && getFrameTail()
          .equals(other.getFrameTail());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FRAME_HEAD_FIELD_NUMBER;
      hash = (53 * hash) + getFrameHead().hashCode();
      hash = (37 * hash) + DIR_FIELD_NUMBER;
      hash = (53 * hash) + getDir().hashCode();
      hash = (37 * hash) + COMMUNICATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getCommunicationID().hashCode();
      hash = (37 * hash) + SIMCCID_FIELD_NUMBER;
      hash = (53 * hash) + getSIMCCID().hashCode();
      hash = (37 * hash) + PRODUC_FIELD_NUMBER;
      hash = (53 * hash) + getProduc().hashCode();
      hash = (37 * hash) + COMM_FIELD_NUMBER;
      hash = (53 * hash) + getComm().hashCode();
      hash = (37 * hash) + DATA_LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getDataLength().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + FRAME_TAIL_FIELD_NUMBER;
      hash = (53 * hash) + getFrameTail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IOTValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IOTValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IOTValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IOTValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IOTValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IOTValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IOTValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IOTValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IOTValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IOTValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IOTValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IOTValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IOTValue)
        IOTValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IOTValueProto.internal_static_IOTValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IOTValueProto.internal_static_IOTValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IOTValue.class, Builder.class);
      }

      // Construct using com.haro.netty.iot.staticOfFinal.proto.IOTValueProto.IOTValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        frameHead_ = com.google.protobuf.ByteString.EMPTY;

        dir_ = com.google.protobuf.ByteString.EMPTY;

        communicationID_ = com.google.protobuf.ByteString.EMPTY;

        sIMCCID_ = com.google.protobuf.ByteString.EMPTY;

        produc_ = com.google.protobuf.ByteString.EMPTY;

        comm_ = com.google.protobuf.ByteString.EMPTY;

        dataLength_ = com.google.protobuf.ByteString.EMPTY;

        data_ = com.google.protobuf.ByteString.EMPTY;

        frameTail_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IOTValueProto.internal_static_IOTValue_descriptor;
      }

      public IOTValue getDefaultInstanceForType() {
        return IOTValue.getDefaultInstance();
      }

      public IOTValue build() {
        IOTValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IOTValue buildPartial() {
        IOTValue result = new IOTValue(this);
        result.frameHead_ = frameHead_;
        result.dir_ = dir_;
        result.communicationID_ = communicationID_;
        result.sIMCCID_ = sIMCCID_;
        result.produc_ = produc_;
        result.comm_ = comm_;
        result.dataLength_ = dataLength_;
        result.data_ = data_;
        result.frameTail_ = frameTail_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IOTValue) {
          return mergeFrom((IOTValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IOTValue other) {
        if (other == IOTValue.getDefaultInstance()) return this;
        if (other.getFrameHead() != com.google.protobuf.ByteString.EMPTY) {
          setFrameHead(other.getFrameHead());
        }
        if (other.getDir() != com.google.protobuf.ByteString.EMPTY) {
          setDir(other.getDir());
        }
        if (other.getCommunicationID() != com.google.protobuf.ByteString.EMPTY) {
          setCommunicationID(other.getCommunicationID());
        }
        if (other.getSIMCCID() != com.google.protobuf.ByteString.EMPTY) {
          setSIMCCID(other.getSIMCCID());
        }
        if (other.getProduc() != com.google.protobuf.ByteString.EMPTY) {
          setProduc(other.getProduc());
        }
        if (other.getComm() != com.google.protobuf.ByteString.EMPTY) {
          setComm(other.getComm());
        }
        if (other.getDataLength() != com.google.protobuf.ByteString.EMPTY) {
          setDataLength(other.getDataLength());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getFrameTail() != com.google.protobuf.ByteString.EMPTY) {
          setFrameTail(other.getFrameTail());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IOTValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IOTValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString frameHead_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes frame_head = 1;</code>
       */
      public com.google.protobuf.ByteString getFrameHead() {
        return frameHead_;
      }
      /**
       * <code>bytes frame_head = 1;</code>
       */
      public Builder setFrameHead(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        frameHead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes frame_head = 1;</code>
       */
      public Builder clearFrameHead() {
        
        frameHead_ = getDefaultInstance().getFrameHead();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dir_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes dir = 2;</code>
       */
      public com.google.protobuf.ByteString getDir() {
        return dir_;
      }
      /**
       * <code>bytes dir = 2;</code>
       */
      public Builder setDir(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes dir = 2;</code>
       */
      public Builder clearDir() {
        
        dir_ = getDefaultInstance().getDir();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString communicationID_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes CommunicationID = 3;</code>
       */
      public com.google.protobuf.ByteString getCommunicationID() {
        return communicationID_;
      }
      /**
       * <code>bytes CommunicationID = 3;</code>
       */
      public Builder setCommunicationID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        communicationID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes CommunicationID = 3;</code>
       */
      public Builder clearCommunicationID() {
        
        communicationID_ = getDefaultInstance().getCommunicationID();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString sIMCCID_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes SIMCCID = 4;</code>
       */
      public com.google.protobuf.ByteString getSIMCCID() {
        return sIMCCID_;
      }
      /**
       * <code>bytes SIMCCID = 4;</code>
       */
      public Builder setSIMCCID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sIMCCID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes SIMCCID = 4;</code>
       */
      public Builder clearSIMCCID() {
        
        sIMCCID_ = getDefaultInstance().getSIMCCID();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString produc_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes Produc = 5;</code>
       */
      public com.google.protobuf.ByteString getProduc() {
        return produc_;
      }
      /**
       * <code>bytes Produc = 5;</code>
       */
      public Builder setProduc(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        produc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes Produc = 5;</code>
       */
      public Builder clearProduc() {
        
        produc_ = getDefaultInstance().getProduc();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString comm_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes comm = 6;</code>
       */
      public com.google.protobuf.ByteString getComm() {
        return comm_;
      }
      /**
       * <code>bytes comm = 6;</code>
       */
      public Builder setComm(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes comm = 6;</code>
       */
      public Builder clearComm() {
        
        comm_ = getDefaultInstance().getComm();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dataLength_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data_length = 7;</code>
       */
      public com.google.protobuf.ByteString getDataLength() {
        return dataLength_;
      }
      /**
       * <code>bytes data_length = 7;</code>
       */
      public Builder setDataLength(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data_length = 7;</code>
       */
      public Builder clearDataLength() {
        
        dataLength_ = getDefaultInstance().getDataLength();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 8;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 8;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 8;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString frameTail_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes frame_tail = 9;</code>
       */
      public com.google.protobuf.ByteString getFrameTail() {
        return frameTail_;
      }
      /**
       * <code>bytes frame_tail = 9;</code>
       */
      public Builder setFrameTail(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        frameTail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes frame_tail = 9;</code>
       */
      public Builder clearFrameTail() {
        
        frameTail_ = getDefaultInstance().getFrameTail();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:IOTValue)
    }

    // @@protoc_insertion_point(class_scope:IOTValue)
    private static final IOTValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IOTValue();
    }

    public static IOTValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IOTValue>
        PARSER = new com.google.protobuf.AbstractParser<IOTValue>() {
      public IOTValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new IOTValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IOTValue> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<IOTValue> getParserForType() {
      return PARSER;
    }

    public IOTValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IOTValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IOTValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016IOTValue.proto\"\252\001\n\010IOTValue\022\022\n\nframe_h" +
      "ead\030\001 \001(\014\022\013\n\003dir\030\002 \001(\014\022\027\n\017CommunicationI" +
      "D\030\003 \001(\014\022\017\n\007SIMCCID\030\004 \001(\014\022\016\n\006Produc\030\005 \001(\014" +
      "\022\014\n\004comm\030\006 \001(\014\022\023\n\013data_length\030\007 \001(\014\022\014\n\004d" +
      "ata\030\010 \001(\014\022\022\n\nframe_tail\030\t \001(\014B7\n&com.har" +
      "o.netty.iot.staticOfFinal.protoB\rIOTValu" +
      "eProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IOTValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IOTValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IOTValue_descriptor,
        new String[] { "FrameHead", "Dir", "CommunicationID", "SIMCCID", "Produc", "Comm", "DataLength", "Data", "FrameTail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
